### ISSUE TITLE
Run.sh duplicated

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8a5g#2]
Hi!

Why is there a run_search.sh and a run_predict.sh? as far as I can tell they are both doing the same?

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
Yes, both are doing the same thing. I think the contributor did this in some confusion or what, because initially the `service.py` has api `search` rather than `predict`. But both files has same code inside i.e. ` python $1/code/main.py $2 $3` with just different names. In refactoring, i deleted one of them and renamed second one with `run.sh`.

Thanks.

**Comment by GemmaTuron** [comment]
Thanks, I'll close this issue!
